name: "curl"
description: ""
inputs:
  command:
    description: "Command to execute"
    required: true
    default: 'echo "You forgot command"'
outputs:
  stdout:
    description: "Standard output from task."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
