name: "curl"
description: ""
inputs:
  args:
    description: "args to execute"
    required: true
    default: 'echo "You forgot args"'
outputs:
  stdout:
    description: "Standard output from task."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
