name: CI

on: [push]

jobs:
  test-setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Test LXD action
        uses: lcherone/gh-actions/lxd@master
        with:
          # remote
          remote: |
            {
              "name": "${{ secrets.LXD_REMOTE_NAME }}",
              "url": "${{ secrets.LXD_REMOTE_URL }}",
              "secret": "${{ secrets.LXD_REMOTE_SECRET }}",
              "protocol": "lxd",
              "auth-type": "tls"
            }
          # or like
          # remote-name: "${{ secrets.LXD_REMOTE_NAME }}"
          # remote-url: "${{ secrets.LXD_REMOTE_URL }}"
          # remote-secret: "${{ secrets.LXD_REMOTE_SECRET }}"
          # remote-protocol: "lxd"
          # remote-auth-type: "tls"

          #
          script: |
            result = await lxc.containers.exec(input.remote['name'], 'test-alpine', {
                "command": ["/bin/sh", "-c", "echo Hello from inside container"],
                "environment": {},
                "wait-for-websocket": false,
                "record-output": false,
                "interactive": false,
                "width": 80,
                "height": 25
            })

          #container-name: ''
          #container-action: ''
          #container-exec: ''
          command: |
            lxc list ${{ secrets.LXD_REMOTE_NAME }}:

#
