name: CI

on: [push]

jobs:
  test-setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Test LXD action
        uses: lcherone/gh-actions/lxd@master
        env:
          LXD_SECRET: testing
        with:
          #remote-name: ''
          #remote-url: ''
          #remote-secret: ''
          #container-name: ''
          #container-action: ''
          script: |
            lxc remote add ${{ secrets.LXD_REMOTE_NAME }} ${{ secrets.LXD_REMOTE_URL }} \
            --accept-certificate --protocol=lxd --auth-type=tls --password=${{ secrets.LXD_REMOTE_SECRET }}
#
